// Generated by gencpp from file mindrove_package/MindRoveData.msg
// DO NOT EDIT!


#ifndef MINDROVE_PACKAGE_MESSAGE_MINDROVEDATA_H
#define MINDROVE_PACKAGE_MESSAGE_MINDROVEDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mindrove_package
{
template <class ContainerAllocator>
struct MindRoveData_
{
  typedef MindRoveData_<ContainerAllocator> Type;

  MindRoveData_()
    : data()  {
      data.assign(0.0);
  }
  MindRoveData_(const ContainerAllocator& _alloc)
    : data()  {
  (void)_alloc;
      data.assign(0.0);
  }



   typedef boost::array<double, 14000>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::mindrove_package::MindRoveData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mindrove_package::MindRoveData_<ContainerAllocator> const> ConstPtr;

}; // struct MindRoveData_

typedef ::mindrove_package::MindRoveData_<std::allocator<void> > MindRoveData;

typedef boost::shared_ptr< ::mindrove_package::MindRoveData > MindRoveDataPtr;
typedef boost::shared_ptr< ::mindrove_package::MindRoveData const> MindRoveDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mindrove_package::MindRoveData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mindrove_package::MindRoveData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mindrove_package::MindRoveData_<ContainerAllocator1> & lhs, const ::mindrove_package::MindRoveData_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mindrove_package::MindRoveData_<ContainerAllocator1> & lhs, const ::mindrove_package::MindRoveData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mindrove_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mindrove_package::MindRoveData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mindrove_package::MindRoveData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mindrove_package::MindRoveData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mindrove_package::MindRoveData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mindrove_package::MindRoveData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mindrove_package::MindRoveData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mindrove_package::MindRoveData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86daf2bf043daacec99b385ed93f47b1";
  }

  static const char* value(const ::mindrove_package::MindRoveData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86daf2bf043daaceULL;
  static const uint64_t static_value2 = 0xc99b385ed93f47b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::mindrove_package::MindRoveData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mindrove_package/MindRoveData";
  }

  static const char* value(const ::mindrove_package::MindRoveData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mindrove_package::MindRoveData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[14000] data\n"
;
  }

  static const char* value(const ::mindrove_package::MindRoveData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mindrove_package::MindRoveData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MindRoveData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mindrove_package::MindRoveData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mindrove_package::MindRoveData_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINDROVE_PACKAGE_MESSAGE_MINDROVEDATA_H
